//application.js
export const SET_CHANNEL = 'SET_CHANNEL'
export const SET_BROADCASTER_TYPE = 'SET_BROADCASTER_TYPE'
export const SET_JWT_TOKEN = 'SET_JWT_TOKEN'
export const SET_CURRENT_APP = 'SET_CURRENT_APP'
export const SET_MODS = 'SET_MODS'

//apps.js
export const SET_AVAILABLE_APPS = 'SET_AVAILABLE_APPS'
export const SET_MY_APPS = 'SET_MY_APPS'

//APPS
//channelPointsManager.js
export const CREATE_REWARD = 'CREATE_REWARD'
export const DISPLAY_FORM = 'DISPLAY_FORM'
export const SET_NEW_REWARD_ID = 'SET_NEW_REWARD_ID'
export const CANCEL_FORM = 'CANCEL_FORM'
export const DELETE_FORM = 'DELETE_FORM'
export const DELETE_FAILED_REWARD = 'DELETE_FAILED_REWARD'
export const CLEAR_REWARDS = 'CLEAR_REWARDS'

export const SET_CHANNEL_POINT_ALERT = 'SET_CHANNEL_POINT_ALERT'

export const HANDLE_COLOR_CHANGE_COMPLETE = 'HANDLE_COLOR_CHANGE_COMPLETE'
export const TOGGLE_COLOR_SELECT = 'TOGGLE_COLOR_SELECT'
export const SHOW_CUSTOM_PICKER = 'SHOW_CUSTOM_PICKER'
export const TOGGLE_HANDLER = 'TOGGLE_HANDLER'
export const ON_SELECT = 'ON_SELECT'
export const SET_INPUT_VALUE = 'SET_INPUT_VALUE'
export const SET_INPUT_ARRAY_VALUE = 'SET_INPUT_ARRAY_VALUE'
export const REMOVE_INPUT_ARRAY_VALUE = 'REMOVE_INPUT_ARRAY_VALUE'
export const INSERT_INPUT_ARRAY_VALUE = 'INSERT_INPUT_ARRAY_VALUE'
export const TOGGLE_REWARD_STATUS = 'TOGGLE_REWARD_STATUS'
export const SET_CURRENT_DISPLAY = 'SET_CURRENT_DISPLAY'
export const SET_CUSTOM_SETTINGS = 'SET_CUSTOM_SETTINGS'